# Generated by Django 4.2.16 on 2024-11-07 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('floors', models.PositiveSmallIntegerField(verbose_name='Количество этажей')),
                ('date_of_construction', models.DateField(verbose_name='Дата постройки дома')),
                ('date_of_delivery', models.DateField(verbose_name='Дата сдачи дома')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='Номер дома')),
                ('status', models.CharField(choices=[('Under construction', 'Строится'), ('Passed', 'Сдан')], default='Under construction', max_length=25, verbose_name='Статус')),
                ('type', models.CharField(blank=True, choices=[('Brick', 'Кирпичный'), ('Monolithic', 'Монолитный'), ('Panel', 'Панельный')], max_length=10, null=True, verbose_name='Тип дома')),
                ('has_parking', models.BooleanField(default=True, verbose_name='Паркинг')),
                ('elevators', models.IntegerField(choices=[(0, 'Ноль'), (1, 'Один'), (2, 'Два'), (3, 'Три')], default=2, verbose_name='Лифты')),
            ],
        ),
        migrations.CreateModel(
            name='FlatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Economy', 'Эконом'), ('Comfort', 'Комфорт'), ('Luxe', 'Люкс')], db_index=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этаж',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название секции')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='Номер секции')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Общая площадь')),
                ('living_space', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Жилая площадь')),
                ('kitchen_area', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Площадь кухни')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('status', models.CharField(choices=[('On sale', 'В продаже'), ('Sold', 'Продана')], default='On sale', max_length=7, verbose_name='Статус')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.building', verbose_name='Дом')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.flatcategory', verbose_name='Класс квартиры')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.floor', verbose_name='Этаж')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.project'),
        ),
    ]
