# Generated by Django 4.2.16 on 2024-11-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_section_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='building',
        ),
    ]
