# Generated by Django 5.0.2 on 2024-10-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_section_alter_building_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='building',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.building'),
        ),
    ]
