# Generated by Django 5.0.2 on 2024-10-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_section_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='realty.section', verbose_name='Секция'),
        ),
    ]
