# Generated by Django 5.0.2 on 2024-10-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_flat_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='section',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.building'),
        ),
    ]
