# Generated by Django 4.2.16 on 2024-11-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_alter_section_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='building',
        ),
    ]
