# Generated by Django 4.2.16 on 2024-11-17 16:50

from django.db import migrations, models
import realty.models.building
import realty.models.flat
import realty.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_remove_section_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(default=1, upload_to=realty.models.building.Building.upload_to, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default=1, upload_to=realty.models.project.Project.upload_to, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='photo',
            field=models.ImageField(upload_to=realty.models.flat.Flat.upload_to, verbose_name='Изображение'),
        ),
    ]
