# Generated by Django 4.2.16 on 2024-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_alter_building_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=models.ImageField(upload_to='photos/building/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='photo',
            field=models.ImageField(upload_to='photos/flat/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='photos/project/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
