# Generated by Django 4.2.16 on 2024-11-16 17:14

from django.db import migrations, models
import realty.models.building


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_alter_building_photo_alter_flat_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=models.ImageField(upload_to=realty.models.building.Building.upload_to, verbose_name='Изображение'),
        ),
    ]
