# Generated by Django 4.2.16 on 2024-11-16 17:33

from django.db import migrations, models
import realty.models.flat


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_alter_building_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='photo',
            field=models.ImageField(upload_to=realty.models.flat.Flat.upload_to, verbose_name='Изображение'),
        ),
    ]
