# Generated by Django 4.2.16 on 2024-11-16 17:39

from django.db import migrations, models
import realty.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_alter_flat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to=realty.models.project.Project.upload_to, verbose_name='Изображение'),
        ),
    ]
